name: ghpages.yml

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - '/**'
      - '!.gitignore'
      - '!README.md'

defaults:
  run:
    working-directory: vue

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn run build --if-present
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: 'main'
          publish_branch: gh-pages
          publish_dir: ./ghpages
